[[main]]
name = "Robbie"
pageRef = "/"
weight = 10

[[main]]
name = "Uitvaart"
pageRef = "/uitvaart/"
weight = 20

[[main]]
name = "Galerie"
pageRef = "/galerie_intro/"
weight = 30

[[main]]
name = "Contact"
pageRef = "/contact/"
weight = 40

# [[main]]
# name = "Gallerie"
# pageRef = "/galerie/"
# weight = 60