baseURL = 'https://robbiegeldof.nl/'
locale = 'nl-NL'
title = 'Robbie Geldof'
enableRobotsTXT = true



# [module]
# [[module.imports]]
# disable = false
# ignoreConfig = false
# ignoreImports = false
# path = 'github.com/gohugo-ananke/ananke/v2'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
